package cmodule.desc
{
   public function modStaticInit() : void
   {
      _AS3_ArrayValue = importSym("_AS3_ArrayValue");
      _AS3_Int = importSym("_AS3_Int");
      _AS3_Function = importSym("_AS3_Function");
      _AS3_Object = importSym("_AS3_Object");
      _AS3_Release = importSym("_AS3_Release");
      _abort = importSym("_abort");
      modPreStaticInit();
      gstaticInitter.start(__2E_str);
      gstaticInitter.asciz = "_fini";
      gstaticInitter.start(__2E_str1);
      gstaticInitter.asciz = "_init";
      gstaticInitter.start(_val_2E_939);
      gstaticInitter.zero = 4;
      gstaticInitter.start(__2E_str8);
      gstaticInitter.asciz = "mmap anon";
      gstaticInitter.start(__2E_str311);
      gstaticInitter.asciz = "munmap";
      gstaticInitter.start(__2E_str4);
      gstaticInitter.asciz = "madvise";
      gstaticInitter.start(__2E_str37);
      gstaticInitter.asciz = "sigaction";
      gstaticInitter.start(__2E_str138);
      gstaticInitter.asciz = "signal_glue.c";
      gstaticInitter.start(__2E_str441);
      gstaticInitter.asciz = "sigprocmask";
      gstaticInitter.start(__2E_str643);
      gstaticInitter.asciz = "kill";
      gstaticInitter.start(__2E_str150);
      gstaticInitter.asciz = "stat_glue.c";
      gstaticInitter.start(___mb_cur_max_2E_b);
      gstaticInitter.zero = 1;
      gstaticInitter.start(__2E_str169);
      gstaticInitter.asciz = "unistd_glue.c";
      gstaticInitter.start(__2E_str775);
      gstaticInitter.asciz = "getpid";
      gstaticInitter.start(__2E_str1679);
      gstaticInitter.asciz = "issetugid";
      gstaticInitter.start(__2E_str95);
      gstaticInitter.asciz = "__seterrno(%d, %s, %d)";
      gstaticInitter.start(___progname);
      gstaticInitter.i32 = __2E_str58;
      gstaticInitter.start(__2E_str58);
      gstaticInitter.zero = 1;
      gstaticInitter.start(_environ);
      gstaticInitter.zero = 4;
      gstaticInitter.start(__2E_str161);
      gstaticInitter.asciz = "Infinity";
      gstaticInitter.start(__2E_str262);
      gstaticInitter.asciz = "NaN";
      gstaticInitter.start(___tens_D2A);
      gstaticInitter.i32 = 0;
      gstaticInitter.i32 = 1072693248;
      gstaticInitter.i32 = 0;
      gstaticInitter.i32 = 1076101120;
      gstaticInitter.i32 = 0;
      gstaticInitter.i32 = 1079574528;
      gstaticInitter.i32 = 0;
      gstaticInitter.i32 = 1083129856;
      gstaticInitter.i32 = 0;
      gstaticInitter.i32 = 1086556160;
      gstaticInitter.i32 = 0;
      gstaticInitter.i32 = 1090021888;
      gstaticInitter.i32 = 0;
      gstaticInitter.i32 = 1093567616;
      gstaticInitter.i32 = 0;
      gstaticInitter.i32 = 1097011920;
      gstaticInitter.i32 = 0;
      gstaticInitter.i32 = 1100470148;
      gstaticInitter.i32 = 0;
      gstaticInitter.i32 = 1104006501;
      gstaticInitter.i32 = 536870912;
      gstaticInitter.i32 = 1107468383;
      gstaticInitter.i32 = 3892314112;
      gstaticInitter.i32 = 1110919286;
      gstaticInitter.i32 = 2717908992;
      gstaticInitter.i32 = 1114446484;
      gstaticInitter.i32 = 3846176768;
      gstaticInitter.i32 = 1117925532;
      gstaticInitter.i32 = 512753664;
      gstaticInitter.i32 = 1121369284;
      gstaticInitter.i32 = 640942080;
      gstaticInitter.i32 = 1124887541;
      gstaticInitter.i32 = 937459712;
      gstaticInitter.i32 = 1128383353;
      gstaticInitter.i32 = 2245566464;
      gstaticInitter.i32 = 1131820119;
      gstaticInitter.i32 = 1733216256;
      gstaticInitter.i32 = 1135329645;
      gstaticInitter.i32 = 1620131072;
      gstaticInitter.i32 = 1138841828;
      gstaticInitter.i32 = 2025163840;
      gstaticInitter.i32 = 1142271773;
      gstaticInitter.i32 = 3605196624;
      gstaticInitter.i32 = 1145772772;
      gstaticInitter.i32 = 105764242;
      gstaticInitter.i32 = 1149300943;
      gstaticInitter.start(___bigtens_D2A);
      gstaticInitter.i32 = 937459712;
      gstaticInitter.i32 = 1128383353;
      gstaticInitter.i32 = 3037031959;
      gstaticInitter.i32 = 1184086197;
      gstaticInitter.i32 = 3913284085;
      gstaticInitter.i32 = 1295535875;
      gstaticInitter.i32 = 4180679986;
      gstaticInitter.i32 = 1518499656;
      gstaticInitter.i32 = 2138292028;
      gstaticInitter.i32 = 1964330973;
      gstaticInitter.start(_pmem_next);
      gstaticInitter.i32 = _private_mem;
      gstaticInitter.start(_private_mem);
      gstaticInitter.zero = 2304;
      gstaticInitter.start(_freelist);
      gstaticInitter.zero = 64;
      gstaticInitter.start(_p05_2E_3275);
      gstaticInitter.i32 = 5;
      gstaticInitter.i32 = 25;
      gstaticInitter.i32 = 125;
      gstaticInitter.start(_p5s);
      gstaticInitter.zero = 4;
      gstaticInitter.start(_initial_2E_1635);
      gstaticInitter.zero = 128;
      gstaticInitter.start(___mlocale_changed_2E_b);
      gstaticInitter.zero = 1;
      gstaticInitter.start(__2E_str20157);
      gstaticInitter.asciz = ".";
      gstaticInitter.start(_numempty22);
      gstaticInitter.asciz = "";
      gstaticInitter.start(___nlocale_changed_2E_b);
      gstaticInitter.zero = 1;
      gstaticInitter.start(_ret_2E_993_2E_0);
      gstaticInitter.zero = 4;
      gstaticInitter.start(_ret_2E_993_2E_1);
      gstaticInitter.zero = 4;
      gstaticInitter.start(_ret_2E_993_2E_2);
      gstaticInitter.zero = 4;
      gstaticInitter.start(___sF);
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.i16 = 4;
      gstaticInitter.zero = 2;
      gstaticInitter.zero = 8;
      gstaticInitter.zero = 4;
      gstaticInitter.i32 = ___sF;
      gstaticInitter.i32 = ___sclose;
      gstaticInitter.i32 = ___sread;
      gstaticInitter.i32 = ___sseek;
      gstaticInitter.i32 = ___swrite;
      gstaticInitter.zero = 8;
      gstaticInitter.i32 = ___sFX;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 3;
      gstaticInitter.zero = 1;
      gstaticInitter.zero = 8;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 8;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.i16 = 8;
      gstaticInitter.i16 = 1;
      gstaticInitter.zero = 8;
      gstaticInitter.zero = 4;
      gstaticInitter.i32 = ___sF + 88;
      gstaticInitter.i32 = ___sclose;
      gstaticInitter.i32 = ___sread;
      gstaticInitter.i32 = ___sseek;
      gstaticInitter.i32 = ___swrite;
      gstaticInitter.zero = 8;
      gstaticInitter.i32 = ___sFX + 152;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 3;
      gstaticInitter.zero = 1;
      gstaticInitter.zero = 8;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 8;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.i16 = 10;
      gstaticInitter.i16 = 2;
      gstaticInitter.zero = 8;
      gstaticInitter.zero = 4;
      gstaticInitter.i32 = ___sF + 176;
      gstaticInitter.i32 = ___sclose;
      gstaticInitter.i32 = ___sread;
      gstaticInitter.i32 = ___sseek;
      gstaticInitter.i32 = ___swrite;
      gstaticInitter.zero = 8;
      gstaticInitter.i32 = ___sFX + 304;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 3;
      gstaticInitter.zero = 1;
      gstaticInitter.zero = 8;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 8;
      gstaticInitter.start(___sglue);
      gstaticInitter.i32 = _uglue;
      gstaticInitter.i32 = 3;
      gstaticInitter.i32 = ___sF;
      gstaticInitter.start(_uglue);
      gstaticInitter.zero = 4;
      gstaticInitter.i32 = 17;
      gstaticInitter.i32 = _usual;
      gstaticInitter.start(_usual);
      gstaticInitter.zero = 1496;
      gstaticInitter.start(___sFX);
      gstaticInitter.zero = 456;
      gstaticInitter.start(___sdidinit_2E_b);
      gstaticInitter.zero = 1;
      gstaticInitter.start(_usual_extra);
      gstaticInitter.zero = 2584;
      gstaticInitter.start(___cleanup_2E_b);
      gstaticInitter.zero = 1;
      gstaticInitter.start(_blanks_2E_4034);
      gstaticInitter.ascii = "                ";
      gstaticInitter.start(_zeroes_2E_4035);
      gstaticInitter.ascii = "0000000000000000";
      gstaticInitter.start(_xdigs_lower_2E_4036);
      gstaticInitter.ascii = "0123456789abcdef?";
      gstaticInitter.start(_xdigs_upper_2E_4037);
      gstaticInitter.ascii = "0123456789ABCDEF?";
      gstaticInitter.start(__2E_str118276);
      gstaticInitter.asciz = "nan";
      gstaticInitter.start(__2E_str219277);
      gstaticInitter.asciz = "NAN";
      gstaticInitter.start(__2E_str320278);
      gstaticInitter.asciz = "inf";
      gstaticInitter.start(__2E_str421);
      gstaticInitter.asciz = "INF";
      gstaticInitter.start(__2E_str522);
      gstaticInitter.asciz = "(null)";
      gstaticInitter.start(___atexit0_2E_2520);
      gstaticInitter.zero = 520;
      gstaticInitter.start(___atexit);
      gstaticInitter.zero = 4;
      gstaticInitter.start(_malloc_junk_2E_b);
      gstaticInitter.zero = 1;
      gstaticInitter.start(_malloc_hint_2E_b);
      gstaticInitter.zero = 1;
      gstaticInitter.start(_malloc_cache);
      gstaticInitter.i32 = 16;
      gstaticInitter.start(_malloc_origo);
      gstaticInitter.zero = 4;
      gstaticInitter.start(_last_index);
      gstaticInitter.zero = 4;
      gstaticInitter.start(_page_dir);
      gstaticInitter.zero = 4;
      gstaticInitter.start(_px);
      gstaticInitter.zero = 4;
      gstaticInitter.start(_free_list);
      gstaticInitter.zero = 20;
      gstaticInitter.start(_malloc_brk);
      gstaticInitter.zero = 4;
      gstaticInitter.start(_malloc_ninfo);
      gstaticInitter.zero = 4;
      gstaticInitter.start(_malloc_zero_2E_b);
      gstaticInitter.zero = 1;
      gstaticInitter.start(_malloc_active_2E_3023);
      gstaticInitter.zero = 4;
      gstaticInitter.start(_malloc_started_2E_3024_2E_b);
      gstaticInitter.zero = 1;
      gstaticInitter.start(__2E_str113328);
      gstaticInitter.asciz = "MALLOC_OPTIONS";
      gstaticInitter.start(_malloc_realloc_2E_b);
      gstaticInitter.zero = 1;
      gstaticInitter.start(_malloc_sysv_2E_b);
      gstaticInitter.zero = 1;
      gstaticInitter.start(_smodes);
      gstaticInitter.zero = 164;
      gstaticInitter.i32 = 1;
      gstaticInitter.i32 = 2;
      gstaticInitter.i32 = 256;
      gstaticInitter.i32 = 224;
      gstaticInitter.i32 = 256;
      gstaticInitter.i32 = 224;
      gstaticInitter.i32 = 32;
      gstaticInitter.i32 = 1;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.i32 = 3;
      gstaticInitter.i32 = 4;
      gstaticInitter.i32 = 16;
      gstaticInitter.i32 = 8;
      gstaticInitter.zero = 4;
      gstaticInitter.i32 = 24;
      gstaticInitter.i32 = 8;
      gstaticInitter.i32 = 8;
      gstaticInitter.i32 = 8;
      gstaticInitter.i32 = 8;
      gstaticInitter.zero = 64;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.i32 = 2;
      gstaticInitter.i32 = 2;
      gstaticInitter.i32 = 512;
      gstaticInitter.i32 = 448;
      gstaticInitter.i32 = 512;
      gstaticInitter.i32 = 448;
      gstaticInitter.i32 = 32;
      gstaticInitter.i32 = 1;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.i32 = 3;
      gstaticInitter.i32 = 4;
      gstaticInitter.i32 = 16;
      gstaticInitter.i32 = 8;
      gstaticInitter.zero = 4;
      gstaticInitter.i32 = 24;
      gstaticInitter.i32 = 8;
      gstaticInitter.i32 = 8;
      gstaticInitter.i32 = 8;
      gstaticInitter.i32 = 8;
      gstaticInitter.zero = 64;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.i32 = 3;
      gstaticInitter.i32 = 2;
      gstaticInitter.i32 = 640;
      gstaticInitter.i32 = 480;
      gstaticInitter.i32 = 640;
      gstaticInitter.i32 = 480;
      gstaticInitter.i32 = 32;
      gstaticInitter.i32 = 1;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.i32 = 3;
      gstaticInitter.i32 = 4;
      gstaticInitter.i32 = 16;
      gstaticInitter.i32 = 8;
      gstaticInitter.zero = 4;
      gstaticInitter.i32 = 24;
      gstaticInitter.i32 = 8;
      gstaticInitter.i32 = 8;
      gstaticInitter.i32 = 8;
      gstaticInitter.i32 = 8;
      gstaticInitter.zero = 64;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.i32 = 4;
      gstaticInitter.i32 = 2;
      gstaticInitter.i32 = 800;
      gstaticInitter.i32 = 600;
      gstaticInitter.i32 = 800;
      gstaticInitter.i32 = 600;
      gstaticInitter.i32 = 32;
      gstaticInitter.i32 = 1;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.i32 = 3;
      gstaticInitter.i32 = 4;
      gstaticInitter.i32 = 16;
      gstaticInitter.i32 = 8;
      gstaticInitter.zero = 4;
      gstaticInitter.i32 = 24;
      gstaticInitter.i32 = 8;
      gstaticInitter.i32 = 8;
      gstaticInitter.i32 = 8;
      gstaticInitter.i32 = 8;
      gstaticInitter.zero = 64;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.i32 = 5;
      gstaticInitter.i32 = 2;
      gstaticInitter.i32 = 960;
      gstaticInitter.i32 = 720;
      gstaticInitter.i32 = 960;
      gstaticInitter.i32 = 720;
      gstaticInitter.i32 = 32;
      gstaticInitter.i32 = 1;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.i32 = 3;
      gstaticInitter.i32 = 4;
      gstaticInitter.i32 = 16;
      gstaticInitter.i32 = 8;
      gstaticInitter.zero = 4;
      gstaticInitter.i32 = 24;
      gstaticInitter.i32 = 8;
      gstaticInitter.i32 = 8;
      gstaticInitter.i32 = 8;
      gstaticInitter.i32 = 8;
      gstaticInitter.zero = 64;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.i32 = 6;
      gstaticInitter.i32 = 2;
      gstaticInitter.i32 = 1024;
      gstaticInitter.i32 = 768;
      gstaticInitter.i32 = 1024;
      gstaticInitter.i32 = 768;
      gstaticInitter.i32 = 32;
      gstaticInitter.i32 = 1;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.i32 = 3;
      gstaticInitter.i32 = 4;
      gstaticInitter.i32 = 16;
      gstaticInitter.i32 = 8;
      gstaticInitter.zero = 4;
      gstaticInitter.i32 = 24;
      gstaticInitter.i32 = 8;
      gstaticInitter.i32 = 8;
      gstaticInitter.i32 = 8;
      gstaticInitter.i32 = 8;
      gstaticInitter.zero = 64;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.i32 = 7;
      gstaticInitter.i32 = 2;
      gstaticInitter.i32 = 1152;
      gstaticInitter.i32 = 864;
      gstaticInitter.i32 = 1152;
      gstaticInitter.i32 = 864;
      gstaticInitter.i32 = 32;
      gstaticInitter.i32 = 1;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.i32 = 3;
      gstaticInitter.i32 = 4;
      gstaticInitter.i32 = 16;
      gstaticInitter.i32 = 8;
      gstaticInitter.zero = 4;
      gstaticInitter.i32 = 24;
      gstaticInitter.i32 = 8;
      gstaticInitter.i32 = 8;
      gstaticInitter.i32 = 8;
      gstaticInitter.i32 = 8;
      gstaticInitter.zero = 64;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.i32 = 8;
      gstaticInitter.i32 = 2;
      gstaticInitter.i32 = 1280;
      gstaticInitter.i32 = 1024;
      gstaticInitter.i32 = 1280;
      gstaticInitter.i32 = 1024;
      gstaticInitter.i32 = 32;
      gstaticInitter.i32 = 1;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.i32 = 3;
      gstaticInitter.i32 = 4;
      gstaticInitter.i32 = 16;
      gstaticInitter.i32 = 8;
      gstaticInitter.zero = 4;
      gstaticInitter.i32 = 24;
      gstaticInitter.i32 = 8;
      gstaticInitter.i32 = 8;
      gstaticInitter.i32 = 8;
      gstaticInitter.i32 = 8;
      gstaticInitter.zero = 64;
      gstaticInitter.zero = 4;
      gstaticInitter.zero = 4;
      gstaticInitter.start(__2E_str391);
      gstaticInitter.asciz = "GIO_KEYMAP\n";
      gstaticInitter.start(__2E_str1392);
      gstaticInitter.asciz = "  (%d) w: %d h: %d\n";
      gstaticInitter.start(__2E_str2393);
      gstaticInitter.asciz = "CONS_MOUSECTL\n";
      gstaticInitter.start(__2E_str3396);
      gstaticInitter.asciz = "VT_GETMODE\n";
      gstaticInitter.start(__2E_str4397);
      gstaticInitter.asciz = "VGLIOCTL %d\n";
      gstaticInitter.start(_llvm_2E_global_ctors);
      gstaticInitter.start(__2E_str212);
      gstaticInitter.asciz = "IntType, IntType, IntType";
      gstaticInitter.start(__2E_str1213);
      gstaticInitter.asciz = "Desc:AS3ValType";
      modPostStaticInit();
   }
}
